### ISSUE TITLE
Add standard format for input data

### ISSUE THREAD

**Issue by SimonGoring** [RossThorn/FCVS#3]
In the README and in the js package.
What does it need to be?

```
{'Picea':100, 'Pinus':12,'Ghost':120}
```

**Comment by SimonGoring** [comment]
Or with a z axis?
```
{
 time: [10,12,13,14],
 data: {'Picea':100, 'Pinus':12,'Ghost':120}
}
```

**Comment by SimonGoring** [comment]
Tagging @Shane98c and @fils on this as they might have relevant ideas.

**Comment by RossThorn** [comment]
The code now formats Neotoma calls in the desired format as follows:
```
[
  {
  "name": "SiteName1",
  "latitude": 45.7944,
  "longitude": -89.3140,
  "time":
    {
      "1000":
        {
          "Taxa1": 45,
          "Taxa2": 16,
          "Taxa3": 150,
          "Taxa4": 88
           },
      "2000":
        {
          "Taxa1": 50,
          "Taxa2": 24,
          "Taxa3": 120,
          "Taxa4": 67
           }
        }
},
  {
  "name": "SiteName2",
    ...
   }
]
```

It is an array of site objects. Each site object will need latitude and longitude as well as time. Things like SiteName, SiteID, etc are optional. The time key holds an object of keys pertaining to bin values, with each variable holding the appropriate value.

*Thanks Shane for making it more legible!
